// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CommunityResult interface {
	IsCommunityResult()
}

type Article struct {
	ID          string      `json:"id"`
	Title       string      `json:"title"`
	Content     string      `json:"content"`
	Slug        string      `json:"slug"`
	Category    string      `json:"category"`
	Thumbnail   string      `json:"thumbnail"`
	Featured    bool        `json:"featured"`
	Description string      `json:"description"`
	Author      *PublicUser `json:"author"`
	CreatedAt   string      `json:"createdAt"`
	UpdatedAt   string      `json:"updatedAt"`
}

type Category struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	CreatedAt string `json:"createdAt"`
}

type Channel struct {
	ID         string      `json:"id"`
	Name       string      `json:"name"`
	Type       ChannelType `json:"type"`
	Discussion *Discussion `json:"discussion"`
	Messages   []*Message  `json:"messages"`
}

type Comment struct {
	ID           string      `json:"id"`
	Content      string      `json:"content"`
	Author       *PublicUser `json:"author"`
	Post         *Post       `json:"post"`
	ParentID     *string     `json:"parentId,omitempty"`
	Replies      []*Comment  `json:"replies"`
	RepliesCount int32       `json:"repliesCount"`
	Upvotes      int32       `json:"upvotes"`
	Downvotes    int32       `json:"downvotes"`
	UserVote     VoteType    `json:"userVote"`
	CreatedAt    string      `json:"createdAt"`
}

func (Comment) IsCommunityResult() {}

type CompleteSetupInput struct {
	Username    string `json:"username"`
	DisplayName string `json:"displayName"`
}

type Discussion struct {
	ID       string     `json:"id"`
	Group    *Group     `json:"group"`
	Channels []*Channel `json:"channels"`
}

type Group struct {
	ID           string      `json:"id"`
	Name         string      `json:"name"`
	Description  string      `json:"description"`
	Icon         *string     `json:"icon,omitempty"`
	Slug         string      `json:"slug"`
	Type         GroupType   `json:"type"`
	Owner        *PublicUser `json:"owner"`
	MembersCount int32       `json:"membersCount"`
	IsMember     bool        `json:"isMember"`
	Posts        []*Post     `json:"posts"`
	CreatedAt    string      `json:"createdAt"`
}

func (Group) IsCommunityResult() {}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Message struct {
	ID        string      `json:"id"`
	Content   string      `json:"content"`
	Sender    *PublicUser `json:"sender"`
	Channel   *Channel    `json:"channel"`
	CreatedAt string      `json:"createdAt"`
}

type Mutation struct {
}

type NewArticle struct {
	Title     string `json:"title"`
	Content   string `json:"content"`
	Category  string `json:"category"`
	Thumbnail string `json:"thumbnail"`
	Featured  bool   `json:"featured"`
}

type NewChannel struct {
	DiscussionID string      `json:"discussionId"`
	Name         string      `json:"name"`
	Type         ChannelType `json:"type"`
}

type NewComment struct {
	PostID   string  `json:"postId"`
	ParentID *string `json:"parentId,omitempty"`
	Content  string  `json:"content"`
}

type NewGroup struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Type        GroupType `json:"type"`
}

type NewMessage struct {
	ChannelID string `json:"channelId"`
	Content   string `json:"content"`
}

type NewPost struct {
	GroupID string `json:"groupId"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type NewUser struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Email        string `json:"email"`
	Gender       string `json:"gender"`
	PhoneNumber  string `json:"phoneNumber"`
	MachineToken string `json:"machineToken"`
}

type Post struct {
	ID            string      `json:"id"`
	Title         string      `json:"title"`
	Content       string      `json:"content"`
	Author        *PublicUser `json:"author"`
	Group         *Group      `json:"group"`
	CommentsCount int32       `json:"commentsCount"`
	Upvotes       int32       `json:"upvotes"`
	Downvotes     int32       `json:"downvotes"`
	UserVote      VoteType    `json:"userVote"`
	Comments      []*Comment  `json:"comments"`
	CreatedAt     string      `json:"createdAt"`
}

func (Post) IsCommunityResult() {}

type PublicUser struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Username    string     `json:"username"`
	DisplayName string     `json:"displayName"`
	Gender      string     `json:"gender"`
	Avatar      string     `json:"avatar"`
	Posts       []*Post    `json:"posts"`
	Comments    []*Comment `json:"comments"`
	Groups      []*Group   `json:"groups"`
}

type Query struct {
}

type Subscription struct {
}

type UpdateArticle struct {
	ID        string  `json:"id"`
	Title     *string `json:"title,omitempty"`
	Content   *string `json:"content,omitempty"`
	Category  *string `json:"category,omitempty"`
	Thumbnail *string `json:"thumbnail,omitempty"`
	Featured  *bool   `json:"featured,omitempty"`
}

type UpdateUserInput struct {
	Username    *string `json:"username,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
	Avatar      *string `json:"avatar,omitempty"`
}

type User struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Username      string `json:"username"`
	DisplayName   string `json:"displayName"`
	Email         string `json:"email"`
	Gender        string `json:"gender"`
	Avatar        string `json:"avatar"`
	PhoneNumber   string `json:"phoneNumber"`
	SetupComplete bool   `json:"setupComplete"`
	IsAdmin       bool   `json:"isAdmin"`
	IsBanned      bool   `json:"isBanned"`
	CreatedAt     string `json:"createdAt"`
}

type ChannelType string

const (
	ChannelTypeText ChannelType = "TEXT"
)

var AllChannelType = []ChannelType{
	ChannelTypeText,
}

func (e ChannelType) IsValid() bool {
	switch e {
	case ChannelTypeText:
		return true
	}
	return false
}

func (e ChannelType) String() string {
	return string(e)
}

func (e *ChannelType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ChannelType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ChannelType", str)
	}
	return nil
}

func (e ChannelType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ChannelType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ChannelType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GroupType string

const (
	GroupTypePublic  GroupType = "PUBLIC"
	GroupTypePrivate GroupType = "PRIVATE"
)

var AllGroupType = []GroupType{
	GroupTypePublic,
	GroupTypePrivate,
}

func (e GroupType) IsValid() bool {
	switch e {
	case GroupTypePublic, GroupTypePrivate:
		return true
	}
	return false
}

func (e GroupType) String() string {
	return string(e)
}

func (e *GroupType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GroupType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GroupType", str)
	}
	return nil
}

func (e GroupType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GroupType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GroupType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleAdmin Role = "ADMIN"
	RoleUser  Role = "USER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleUser,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleUser:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type VoteType string

const (
	VoteTypeUp   VoteType = "UP"
	VoteTypeDown VoteType = "DOWN"
	VoteTypeNone VoteType = "NONE"
)

var AllVoteType = []VoteType{
	VoteTypeUp,
	VoteTypeDown,
	VoteTypeNone,
}

func (e VoteType) IsValid() bool {
	switch e {
	case VoteTypeUp, VoteTypeDown, VoteTypeNone:
		return true
	}
	return false
}

func (e VoteType) String() string {
	return string(e)
}

func (e *VoteType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VoteType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VoteType", str)
	}
	return nil
}

func (e VoteType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VoteType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VoteType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
